config { 
  type: "table"
}
SELECT
  Retail.Ship_Mode,
  Retail.Segment,
  Retail.Country,
  Retail.City,
  Retail.State,
  Coordinates.LNG,
  Coordinates.LAT,
  Retail.Postal_Code,
  Retail.Region,
  Retail.Category,
  Retail.Sub_Category,
	Retail.Sales,
	Retail.Quantity,
	Retail.Discount,
	Retail.Profit 
FROM
  ${ref("retail_table_better")} as Retail
  LEFT JOIN ${ref("zip_lat_long")} as Coordinates
    ON CAST(Retail.Postal_Code as int) = Coordinates.ZIP
